package com.bookkeeping.core.category;

import com.bookkeeping.common.ResultCode;
import com.bookkeeping.common.enums.CategoryType;
import com.bookkeeping.exception.BusinessException;
import com.bookkeeping.supporting.security.SecurityUtils;
import com.bookkeeping.supporting.user.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {@link CategoryService}.
 * Uses Mockito for repository and SecurityUtils mocking.
 * Uses the REAL generated {@link CategoryDtoMapperConverter} (auto-generated by MapStructPlus)
 * instead of mocking the mapper - this also verifies the mapping logic works correctly.
 *
 * Follows the same patterns as AccountServiceTest and AuthServiceTest.
 */
@ExtendWith(MockitoExtension.class)
class CategoryServiceTest {

    @Mock
    private CategoryRepository categoryRepository;

    @Mock
    private SecurityUtils securityUtils;

    // Use the REAL generated converter - this is auto-generated by MapStructPlus
    // from @MapperAuto on CategoryDto. Verifies that the auto-generated mapping works.
    private final CategoryMapper categoryMapper = new CategoryDtoMapperConverter();

    private CategoryService categoryService;

    private User testUser;
    private Category testCategory;

    @BeforeEach
    void setUp() {
        categoryService = new CategoryService(categoryRepository, categoryMapper, securityUtils);

        testUser = User.builder().username("testuser").build().withId(1L);

        testCategory = Category.builder()
                .name("Groceries")
                .categoryType(CategoryType.EXPENSE)
                .userId(1L)
                .parentId(null)
                .sortOrder(0)
                .hidden(false)
                .icon("mdi-cart")
                .color("#FF5722")
                .comment("Food and household items")
                .build()
                .withId(100L);
    }

    // ========================================================================
    // getCurrentUserCategories
    // ========================================================================

    @Nested
    @DisplayName("getCurrentUserCategories")
    class GetCurrentUserCategories {

        @Test
        @DisplayName("returns mapped DTOs ordered by sortOrder")
        void returns_mapped_dtos() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByUserIdOrderBySortOrderAsc(1L))
                    .thenReturn(List.of(testCategory));

            List<CategoryDto> result = categoryService.getCurrentUserCategories();

            assertEquals(1, result.size());
            CategoryDto dto = result.get(0);
            assertEquals(100L, dto.id());
            assertEquals("Groceries", dto.name());
            assertEquals(CategoryType.EXPENSE, dto.categoryType());
            assertEquals(1L, dto.userId());
            assertEquals("mdi-cart", dto.icon());
            assertEquals("#FF5722", dto.color());
            assertEquals("Food and household items", dto.comment());
            assertFalse(dto.hidden());
            verify(categoryRepository).findByUserIdOrderBySortOrderAsc(1L);
        }

        @Test
        @DisplayName("returns empty list when user has no categories")
        void returns_empty_list() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByUserIdOrderBySortOrderAsc(1L)).thenReturn(List.of());

            List<CategoryDto> result = categoryService.getCurrentUserCategories();

            assertTrue(result.isEmpty());
        }
    }

    // ========================================================================
    // getCategoriesByType
    // ========================================================================

    @Nested
    @DisplayName("getCategoriesByType")
    class GetCategoriesByType {

        @Test
        @DisplayName("returns only categories of the specified type")
        void filters_by_type() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByUserIdAndCategoryTypeOrderBySortOrderAsc(1L, CategoryType.EXPENSE))
                    .thenReturn(List.of(testCategory));

            List<CategoryDto> result = categoryService.getCategoriesByType(CategoryType.EXPENSE);

            assertEquals(1, result.size());
            assertEquals(CategoryType.EXPENSE, result.get(0).categoryType());
        }

        @Test
        @DisplayName("returns empty list when no categories of the type exist")
        void empty_list() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByUserIdAndCategoryTypeOrderBySortOrderAsc(1L, CategoryType.INCOME))
                    .thenReturn(List.of());

            List<CategoryDto> result = categoryService.getCategoriesByType(CategoryType.INCOME);

            assertTrue(result.isEmpty());
        }
    }

    // ========================================================================
    // searchByName
    // ========================================================================

    @Nested
    @DisplayName("searchByName")
    class SearchByName {

        @Test
        @DisplayName("searches by name only when type is null")
        void searches_by_name_only() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByUserIdAndNameContainingIgnoreCase(1L, "Grocery"))
                    .thenReturn(List.of(testCategory));

            List<CategoryDto> result = categoryService.searchByName("Grocery", null);

            assertEquals(1, result.size());
            assertEquals("Groceries", result.get(0).name());
            verify(categoryRepository).findByUserIdAndNameContainingIgnoreCase(1L, "Grocery");
            verify(categoryRepository, never()).findByUserIdAndNameContainingIgnoreCaseAndCategoryType(
                    anyLong(), anyString(), any());
        }

        @Test
        @DisplayName("searches by name and type when both are provided")
        void searches_by_name_and_type() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByUserIdAndNameContainingIgnoreCaseAndCategoryType(
                    1L, "Grocery", CategoryType.EXPENSE))
                    .thenReturn(List.of(testCategory));

            List<CategoryDto> result = categoryService.searchByName("Grocery", CategoryType.EXPENSE);

            assertEquals(1, result.size());
            verify(categoryRepository).findByUserIdAndNameContainingIgnoreCaseAndCategoryType(
                    1L, "Grocery", CategoryType.EXPENSE);
        }
    }

    // ========================================================================
    // createCategory
    // ========================================================================

    @Nested
    @DisplayName("createCategory")
    class CreateCategory {

        @Test
        @DisplayName("creates a category with all fields populated")
        void creates_with_all_fields() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.existsByNameAndUserId("Groceries", 1L)).thenReturn(false);
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            CategoryController.CategoryCreateRequest request = new CategoryController.CategoryCreateRequest(
                    "Groceries", 2, "mdi-cart", "#FF5722", "Food and household items", null);
            CategoryDto result = categoryService.createCategory(request);

            assertNotNull(result);
            assertEquals("Groceries", result.name());
            assertEquals(CategoryType.EXPENSE, result.categoryType());
            assertEquals("mdi-cart", result.icon());
            assertEquals("#FF5722", result.color());

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            Category saved = captor.getValue();
            assertEquals("Groceries", saved.getName());
            assertEquals(CategoryType.EXPENSE, saved.getCategoryType());
            assertEquals(1L, saved.getUserId());
            assertEquals("mdi-cart", saved.getIcon());
            assertEquals("#FF5722", saved.getColor());
            assertEquals("Food and household items", saved.getComment());
            assertEquals(0, saved.getSortOrder());
            assertFalse(saved.getHidden());
        }

        @Test
        @DisplayName("creates a category with parent ID when provided")
        void creates_with_parent() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.existsByNameAndUserId("Subcategory", 1L)).thenReturn(false);
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            CategoryController.CategoryCreateRequest request = new CategoryController.CategoryCreateRequest(
                    "Subcategory", 2, null, null, null, 50L);
            categoryService.createCategory(request);

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            assertEquals(50L, captor.getValue().getParentId());
        }

        @Test
        @DisplayName("throws CATEGORY_TYPE_INVALID when type is null")
        void throws_when_type_null() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);

            CategoryController.CategoryCreateRequest request = new CategoryController.CategoryCreateRequest(
                    "Groceries", null, null, null, null, null);

            BusinessException ex = assertThrows(BusinessException.class,
                    () -> categoryService.createCategory(request));
            assertEquals(ResultCode.CATEGORY_TYPE_INVALID.getCode(), ex.getErrorCode());
            verify(categoryRepository, never()).save(any());
        }

        @Test
        @DisplayName("throws CATEGORY_ALREADY_EXISTS when name is duplicate")
        void throws_when_duplicate_name() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.existsByNameAndUserId("Groceries", 1L)).thenReturn(true);

            CategoryController.CategoryCreateRequest request = new CategoryController.CategoryCreateRequest(
                    "Groceries", 2, null, null, null, null);

            BusinessException ex = assertThrows(BusinessException.class,
                    () -> categoryService.createCategory(request));
            assertEquals(ResultCode.CATEGORY_ALREADY_EXISTS.getCode(), ex.getErrorCode());
            verify(categoryRepository, never()).save(any());
        }

        @Test
        @DisplayName("supports TRANSFER type (value 3)")
        void supports_transfer_type() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.existsByNameAndUserId("Account Transfer", 1L)).thenReturn(false);
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            CategoryController.CategoryCreateRequest request = new CategoryController.CategoryCreateRequest(
                    "Account Transfer", 3, null, null, null, null);
            CategoryDto result = categoryService.createCategory(request);

            assertEquals(CategoryType.TRANSFER, result.categoryType());

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            assertEquals(CategoryType.TRANSFER, captor.getValue().getCategoryType());
        }

        @Test
        @DisplayName("defaults sortOrder to 0 and hidden to false on new category")
        void defaults_sortOrder_and_hidden() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.existsByNameAndUserId(any(), any())).thenReturn(false);
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            CategoryController.CategoryCreateRequest request = new CategoryController.CategoryCreateRequest(
                    "Test", 2, null, null, null, null);
            categoryService.createCategory(request);

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            Category saved = captor.getValue();
            assertEquals(0, saved.getSortOrder());
            assertFalse(saved.getHidden());
        }
    }

    // ========================================================================
    // getCategoryById
    // ========================================================================

    @Nested
    @DisplayName("getCategoryById")
    class GetCategoryById {

        @Test
        @DisplayName("returns Optional with DTO when category exists")
        void returns_dto_when_exists() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(100L, 1L)).thenReturn(Optional.of(testCategory));

            Optional<CategoryDto> result = categoryService.getCategoryById(100L);

            assertTrue(result.isPresent());
            CategoryDto dto = result.get();
            assertEquals("Groceries", dto.name());
            assertEquals("mdi-cart", dto.icon());
        }

        @Test
        @DisplayName("returns empty Optional when category not found")
        void returns_empty_when_not_found() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(999L, 1L)).thenReturn(Optional.empty());

            Optional<CategoryDto> result = categoryService.getCategoryById(999L);

            assertTrue(result.isEmpty());
        }
    }

    // ========================================================================
    // updateCategory
    // ========================================================================

    @Nested
    @DisplayName("updateCategory")
    class UpdateCategory {

        @Test
        @DisplayName("updates all fields when all are provided")
        void updates_all_fields() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(100L, 1L)).thenReturn(Optional.of(testCategory));
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            CategoryController.CategoryUpdateRequest request = new CategoryController.CategoryUpdateRequest(
                    "Updated Groceries", 1, "mdi-food", "#4CAF50", "Updated comment");
            CategoryDto result = categoryService.updateCategory(100L, request);

            assertNotNull(result);
            assertEquals("Updated Groceries", result.name());
            assertEquals(CategoryType.INCOME, result.categoryType());

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            Category saved = captor.getValue();
            assertEquals("Updated Groceries", saved.getName());
            assertEquals(CategoryType.INCOME, saved.getCategoryType());
            assertEquals("mdi-food", saved.getIcon());
            assertEquals("#4CAF50", saved.getColor());
            assertEquals("Updated comment", saved.getComment());
        }

        @Test
        @DisplayName("preserves name when request name is null")
        void preserves_name_when_null() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(100L, 1L)).thenReturn(Optional.of(testCategory));
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            CategoryController.CategoryUpdateRequest request = new CategoryController.CategoryUpdateRequest(
                    null, null, "mdi-food", null, null);
            categoryService.updateCategory(100L, request);

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            assertEquals("Groceries", captor.getValue().getName());
            assertEquals(CategoryType.EXPENSE, captor.getValue().getCategoryType());
            assertEquals("mdi-food", captor.getValue().getIcon());
        }

        @Test
        @DisplayName("preserves category type when request type is null")
        void preserves_type_when_null() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(100L, 1L)).thenReturn(Optional.of(testCategory));
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            CategoryController.CategoryUpdateRequest request = new CategoryController.CategoryUpdateRequest(
                    "New Name", null, null, null, null);
            categoryService.updateCategory(100L, request);

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            assertEquals(CategoryType.EXPENSE, captor.getValue().getCategoryType());
        }

        @Test
        @DisplayName("throws CATEGORY_NOT_FOUND when category does not exist")
        void throws_when_not_found() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(999L, 1L)).thenReturn(Optional.empty());

            CategoryController.CategoryUpdateRequest request = new CategoryController.CategoryUpdateRequest(
                    "Name", 1, null, null, null);

            BusinessException ex = assertThrows(BusinessException.class,
                    () -> categoryService.updateCategory(999L, request));
            assertEquals(ResultCode.CATEGORY_NOT_FOUND.getCode(), ex.getErrorCode());
            verify(categoryRepository, never()).save(any());
        }
    }

    // ========================================================================
    // hideCategory
    // ========================================================================

    @Nested
    @DisplayName("hideCategory")
    class HideCategory {

        @Test
        @DisplayName("hides an unhidden category")
        void hides_category() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(100L, 1L)).thenReturn(Optional.of(testCategory));
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            categoryService.hideCategory(100L, true);

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            assertTrue(captor.getValue().getHidden());
        }

        @Test
        @DisplayName("unhides a hidden category")
        void unhides_category() {
            Category hiddenCategory = testCategory.toBuilder().hidden(true).build();
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(100L, 1L)).thenReturn(Optional.of(hiddenCategory));
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            categoryService.hideCategory(100L, false);

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository).save(captor.capture());
            assertFalse(captor.getValue().getHidden());
        }

        @Test
        @DisplayName("throws CATEGORY_NOT_FOUND when category does not exist")
        void throws_when_not_found() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(999L, 1L)).thenReturn(Optional.empty());

            BusinessException ex = assertThrows(BusinessException.class,
                    () -> categoryService.hideCategory(999L, true));
            assertEquals(ResultCode.CATEGORY_NOT_FOUND.getCode(), ex.getErrorCode());
            verify(categoryRepository, never()).save(any());
        }
    }

    // ========================================================================
    // reorderCategories
    // ========================================================================

    @Nested
    @DisplayName("reorderCategories")
    class ReorderCategories {

        @Test
        @DisplayName("assigns sequential sortOrder starting at 0")
        void assigns_sequential_sortOrder() {
            Category c1 = testCategory.toBuilder().sortOrder(0).build();
            Category c2 = testCategory.toBuilder().sortOrder(1).build();
            Category c3 = testCategory.toBuilder().sortOrder(2).build();

            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(10L, 1L)).thenReturn(Optional.of(c1));
            when(categoryRepository.findByIdAndUserId(20L, 1L)).thenReturn(Optional.of(c2));
            when(categoryRepository.findByIdAndUserId(30L, 1L)).thenReturn(Optional.of(c3));
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            categoryService.reorderCategories(List.of(10L, 20L, 30L));

            ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
            verify(categoryRepository, times(3)).save(captor.capture());
            List<Category> savedCategories = captor.getAllValues();
            assertEquals(0, savedCategories.get(0).getSortOrder());
            assertEquals(1, savedCategories.get(1).getSortOrder());
            assertEquals(2, savedCategories.get(2).getSortOrder());
        }

        @Test
        @DisplayName("does nothing when category list is empty")
        void does_nothing_when_empty() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);

            categoryService.reorderCategories(List.of());

            verify(categoryRepository, never()).findByIdAndUserId(anyLong(), anyLong());
            verify(categoryRepository, never()).save(any());
        }

        @Test
        @DisplayName("throws CATEGORY_NOT_FOUND when a category is not owned by user")
        void throws_when_category_not_owned() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.findByIdAndUserId(10L, 1L)).thenReturn(Optional.of(testCategory));
            when(categoryRepository.findByIdAndUserId(999L, 1L)).thenReturn(Optional.empty());

            BusinessException ex = assertThrows(BusinessException.class,
                    () -> categoryService.reorderCategories(List.of(10L, 999L)));
            assertEquals(ResultCode.CATEGORY_NOT_FOUND.getCode(), ex.getErrorCode());
        }
    }

    // ========================================================================
    // batchCreate
    // ========================================================================

    @Nested
    @DisplayName("batchCreate")
    class BatchCreate {

        @Test
        @DisplayName("creates multiple categories in a single call")
        void creates_multiple() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            List<CategoryService.BatchCreateItem> items = List.of(
                    new CategoryService.BatchCreateItem("Salary", CategoryType.INCOME, null, "mdi-cash", "#4CAF50", null),
                    new CategoryService.BatchCreateItem("Food", CategoryType.EXPENSE, null, "mdi-food", "#FF5722", "Eating out"),
                    new CategoryService.BatchCreateItem("Transfer", CategoryType.TRANSFER, null, null, null, null)
            );

            List<CategoryDto> result = categoryService.batchCreate(items);

            assertEquals(3, result.size());
            verify(categoryRepository, times(3)).save(any(Category.class));
        }

        @Test
        @DisplayName("returns empty list when items is empty")
        void empty_items() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);

            List<CategoryDto> result = categoryService.batchCreate(List.of());

            assertTrue(result.isEmpty());
            verify(categoryRepository, never()).save(any());
        }

        @Test
        @DisplayName("throws CATEGORY_TYPE_INVALID when any item has null type")
        void throws_when_type_null() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);
            when(categoryRepository.save(any(Category.class))).thenAnswer(inv -> inv.getArgument(0));

            List<CategoryService.BatchCreateItem> items = List.of(
                    new CategoryService.BatchCreateItem("Good", CategoryType.INCOME, null, null, null, null),
                    new CategoryService.BatchCreateItem("Bad", null, null, null, null, null)
            );

            BusinessException ex = assertThrows(BusinessException.class,
                    () -> categoryService.batchCreate(items));
            assertEquals(ResultCode.CATEGORY_TYPE_INVALID.getCode(), ex.getErrorCode());
            // The first valid item was saved before the second invalid item caused the exception
            verify(categoryRepository, times(1)).save(any(Category.class));
        }

        @Test
        @DisplayName("throws CATEGORY_TYPE_INVALID when first item has null type")
        void throws_when_first_item_type_null() {
            when(securityUtils.requireCurrentUser()).thenReturn(testUser);

            List<CategoryService.BatchCreateItem> items = List.of(
                    new CategoryService.BatchCreateItem("Bad", null, null, null, null, null)
            );

            BusinessException ex = assertThrows(BusinessException.class,
                    () -> categoryService.batchCreate(items));
            assertEquals(ResultCode.CATEGORY_TYPE_INVALID.getCode(), ex.getErrorCode());
            verify(categoryRepository, never()).save(any());
        }
    }
}
